ALTER TABLE fields
ADD COLUMN IF NOT EXISTS variety VARCHAR(255),
ADD COLUMN IF NOT EXISTS specific_variety VARCHAR(255),
ADD COLUMN IF NOT EXISTS rootstock VARCHAR(255),
ADD COLUMN IF NOT EXISTS planting_year INTEGER,
ADD COLUMN IF NOT EXISTS irrigation_type VARCHAR(255);
